name: Build Windows Release

# on:
#   push:
#     tags:
#       - 'v*.*.*'    # tag with vMAJOR.MINOR.PATCH

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build web
        working-directory: web
        run: |
          npm ci
          npm run build

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller packaging

      - name: Build exe
        run: |
          pyinstaller -y packaging/Umaplay.spec

      - name: Archive artifact
        shell: pwsh
        run: |
          Compress-Archive -Path dist/Umaplay/* -DestinationPath Umaplay-Windows.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: Umaplay-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
